### ISSUE TITLE
Meshes not visible in the editor (4.18.1) version

### ISSUE THREAD

**Issue by Freedom911** [UnrealCourse/05_TestingGrounds#6]
Certain meshes are not present in the editor but are present in the directory.Also I get error  while opening project 
**Error: CDO Constructor Failed to find /Game/Dynamic/Character/Behabiour/Character.Character_C**
**Error:CDO Constructor:Failed to find /Game/Static/Player/Textures/FirstPerson/Crosshair**
​I upgraded to ue 4.18.1 and visual community 2017 recently.

**Comment by sampattuzzi** [comment]
What's the context here?

**Comment by Freedom911** [comment]
![image](https://user-images.githubusercontent.com/9972717/33274297-a999098c-d3b5-11e7-9512-30ba53933153.jpg)
After downloading the project from github and then compiling on UE4.18.1 I am unable to see meshes in the editor window.They are present in the directory.

**Comment by Freedom911** [comment]
As answered by Daniel on udemy Q/A.

>  Files tracked by git lfs won't be in that downloaded zip. You need to clone the repo. You will also get compilation errors due to the build file

I was not aware of that
