### ISSUE TITLE
Blueprint Behaviour Tree Tasks (#215) - Blackboard key NextWaypoint issues

### ISSUE THREAD

**Issue by macfisher** [UnrealCourse/05_TestingGrounds#7]
At 10:10 in lecture #215 there is mention of "NextWaypoint" Blackboard key, which later I re-watched the video to find that it was "renamed off screen" from "Waypoint" in a video footnote.  This through me off because I was working in a separate monitor and did not see that instruction, but that is just a side note for you and not the real issue here...

When the original Blackboard key is created, either "Waypoint" or "NextWaypoint" it needs to be of Base Class "Actor" in order for the key to appear in the Behavior Tree pull-down for "Move To" task. Thank you and excellent work on this course--very thorough and enjoyable.

**Comment by sampattuzzi** [comment]
Thanks Mackenzie. Does this issue show up in the lectures?
